### ISSUE TITLE
Delete / Edit an event

### ISSUE THREAD

**Issue by mdiaz94** [BSeate/Cyber_Snowmen_3155_Project#14]
## **Please describe the feature you wish to add.**
Delete events we don't want anymore, or maybe edit the event for a typo.

## **What is the user story associated with this feature?**
I accidentally created the wrong event and need to delete / edit it.

## **Additional context**
N/a

**Comment by beauseate** [comment]
Basic functionality added in 9f1f5954c1da8ff1b1ed08f071724afa8a216b45
